### ISSUE TITLE
Improve 'duplicate VSM' feature

### ISSUE THREAD

**Issue by askbulle** [equinor/flyt#144]
**User input 1 (by ES - Sharepoint ID113):**
We have duplicated a VSM and roles and time are not copied over. Is there a reason for this? Or could this feature be added?

**User input 2 (by Lise SE, GLB, HE):**
Brukes dupliserings knappen – tar ikke med roller og problem/ideer automatisk. Kun tittel felt som blir kopiert. Alt det det andre må inn påny

**Possible solution:**
When clicking the duplicate button the following dialogue box should appear with choices of what to include in copy
- Problems
- Questions
- Ideas
- Write access/sharing rights
- To-be process
- Categories
- Roles (from #323)
- Durations (from #323)

Default: all above are unchecked

Evaluate if renaming should be done in duplicate dialogue box together with above choices.

**Comment by SayyareHamit** [comment]
Created an issue #653  related to this ticket. 
Otherwise, the features works good.
