### ISSUE TITLE
Process Hierarchy - frontend

### ISSUE THREAD

**Issue by askbulle** [equinor/flyt#157]
**User story**
As a user I want to have parent-child relations between processes so that I can see one process in relation with others. Sub-process in a different colour.. link between mother and daughter

**User input 1 (by HF - SharePoint ID53)**
Hi, I would like to have the opportunity to also create another sipoc within the same window. To be able to do that I need to be able to create another row and then to create green notes. The need of this was discovered when working on amap process. I would be good to visualise the main process and then create sipoc for each of the main steps - within the same window. This to have a more detailed approach to who is the suppliers in each step and what output and customer that are relevant for each step of the main phase. 

**User input 2 (by FL  - SharePoint ID91)**
Some work processes are rather large and it is not suitable to do all stages in one VSM. One way of doing this is to state that it is a selected sub-process that is evaluated. Another option could be to have a main process where you link in new sub-processes along the way (introducing a new button for navigation between VSMs).

**User input 3 (by HSH- SharePoint ID133)**
Option to add phases as one level of lower granularity than the main activities to more easily get the bigger picture overview of the process which will be very useful when you map long and complex processes.

**Describe the solution you'd like**
- New type of card (new colour) in a parent process: LInked child process
- New type of card in the child process: The parent process to be shown on top
- Overview of linked processes: Se på hvordan Miro templaten i link swimlane. hvert kort=1prosess (https://miro.com/miroverse/cross-functional-swimlane-chart/)

**Comment by SjoenH** [comment]
This could be solved 1. quite simple with just a link in an existing card or 2. as a new card type as explained in the requested solution above. 
**_Overview of linked processes_** would require some type of metadata stored. If we go for number solution 2 the metadata could be stored in the new card.

We should also think about what it would look like in the linked-to process.
@Linedueo let's have a talk about this when you have time.

**Comment by askbulle** [comment]
PO's to make sketches of different VSM connections
Workshop with developers + UX designer prior to start

**Comment by VetleW** [comment]
Design for subprocesses: [Here](https://www.figma.com/design/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?node-id=6239-70658&t=KJPSUkbb9ofOQ0sf-4)
Design for chained processes: [Here](https://www.figma.com/design/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?node-id=6239-71209&t=KJPSUkbb9ofOQ0sf-4)

**Comment by KaterynaBasik** [comment]
Discuss:
- the way to unlink  linked process.

**Comment by nesadrian** [comment]
Blocked until backend fix for multiple processcards is implemented

**Comment by nesadrian** [comment]
Remaining:
- [ ] Move process card
- [ ] Center flow when opening form

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with Commit 3e5b69f.
Works as expected.
And agreed to have refinement later in new issues.
