### ISSUE TITLE
Waiting card improvements

### ISSUE THREAD

**Issue by askbulle** [equinor/flyt#162]
**User input (if feedback)**
As a user I would like to add a description text to a waiting box in a similar way as is possible for other boxes like main and sub activities etc.

**Sharepoint ID(s) (if feedback)**
10 

**User story**
As a leader I need to be able to get data on waiting in processes visualized (time & role) to know when follow up by me is necessary

**Describe the solution you'd like**
- probably also valid for descriptions

**Comment by SjoenH** [comment]
Unsure if it is a quick-fix. But shouldn't take too much time.

**Comment by KaterynaBasik** [comment]
Closed by https://github.com/equinor/flyt/issues/721
SharePoint Feedback ID10 has been updated
