### ISSUE TITLE
Feat: Move PQI between yellow cards

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#167]
**User input (if feedback)**
Easy way to move problems, ideas and questions between sub-activities/waiting/choice etc.

**Sharepoint ID(s) (if feedback)**
65

**User story**
As a mapper I would like to easily being able to move PQI between yellow cards

**Comment by VetleW** [comment]
[new design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5823-64955&mode=design&t=WHRbkhkCIFnErGLB-4)

**Comment by AnjaliPandit20** [comment]
@KaterynaBasik , @askbulle  : As confirmed on the backlog refinement call(12/02), closing this issue.
