### ISSUE TITLE
Feat: Improved choice

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#185]
**User input 1 (by TR - Sharepoint ID8)**
I would like to see "Yes" and "No" as text for the "two branches" belonging to a Choice box. As a default "No" branch can be to the right hand side and the "Yes" branch be to the left hand side below the choice diamond.

**User input 2 (by LSE, GLB, HE):**
Når vi skal sammenligne mer enn to dimensjoner, er det mulig å ha flere enn to valg/alternativ? 

**User story**
As an end user I want the choice activities to be intuitive and describing so that it can be used for all needs

**Describe the solution you'd like**
- Label outcomes of choices
- More than two outcomes

**Comment by knudsvik** [comment]
Choice node with text on outcome lines:
![image](https://user-images.githubusercontent.com/25986427/166209081-40bcbdda-8f3c-4db8-a565-83f520699718.png)

**Comment by VetleW** [comment]
[new design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5828-77721&mode=design&t=WHRbkhkCIFnErGLB-4)

**Comment by HavardNot** [comment]
Is there a limit to the number of characters allowed in the choice labels? I am unsure on how to deal with overlapping like this:



![Image](https://github.com/equinor/flyt/assets/110901733/06cd5f3b-85b1-4935-8846-ced372932525)

**Comment by nesadrian** [comment]
This feature is pretty significant so I think we should add a new section in the canvas tutorial.

**Comment by HavardNot** [comment]
> This feature is pretty significant so I think we should add a new section in the canvas tutorial.

Is it the designer that mocks the tutorial section and provides the assets or the developer? @VetleW @nesadrian

**Comment by HavardNot** [comment]
> This feature is pretty significant so I think we should add a new section in the canvas tutorial.

Should this be a new issue or part of this issue?

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
The text on edges of choice card is not entirely shown.

![Image](https://github.com/equinor/flyt/assets/88656616/c41e47fb-3195-442e-9d1b-1fb1b8eb8162)

**Comment by QiJin-Bouvet** [comment]
Tested with commit e5d531a in TEST env.
The text on choice edges looks good.

![Image](https://github.com/equinor/flyt/assets/88656616/5c3cb7ee-68a3-4f30-99ac-d2f8cd5ab56f)
