### ISSUE TITLE
Sum time from sub-actvitites to main activity

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#191]
**User story**
As a user I want the times from sub-activities to be aggregated to the main activity so that I can get better overview of the total time

**Dependency**
Dependent on solution for #163

**Comment by SjoenH** [comment]
Not to hard, can be done in frontend. But might be crashing with #161 .
Discuss and maybe design -> Do we want a fancy summary like a duration per role etc...

**Comment by VetleW** [comment]
Needs some discussion on warning before developement. Otherwise design is ready for developement. 

[Figma design](https://www.figma.com/design/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?node-id=6026-38836&t=C1wxz5RXKQBLNHdT-4)

**Comment by nesadrian** [comment]
Is this the design you had in mind when there are multiple time units @VetleW ?

![Image](https://github.com/equinor/flyt/assets/35768833/5901bf08-1215-44b1-9bed-7f32900b0f9b)

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by nesadrian** [comment]
As discussed in the meeting, we are changing this to have a minimum and a maximum amount of time since choices can create subtrees with different duration.

**Comment by nesadrian** [comment]
We will call the total durations for low estimate and high estimate, as discussed in the meeting

**Comment by nesadrian** [comment]
As discussed in today's meeting we want to emphasize the important difference between working time and waiting time. There may also be a need to cutoff time units in some cases. For example if a process takes years, displaying minutes can be unnecessary. These points should be discussed on the meeting 19.08. 

We will calculate the minimum and maximum time by assuming that there is 7 days a week and 30 days a month.

**Comment by nesadrian** [comment]
Calculation of min and max time is done. Blocked until the previous comment has been discussed.

**Comment by nesadrian** [comment]
As discussed in the meeting we will not round up/down durations. We will also have the text "Low estimate" and "High estimate" in the tooltip and sidebar.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. When the low and high estimate is the same and when there is only one path of cards that has  duration then we display "Estimate: " + duration.

**Comment by QiJin-Bouvet** [comment]
Tested with commit c864e56 in TEST env.
Process is 'destroyed' when having a choice card with loop.

![image](https://github.com/user-attachments/assets/5442286b-806a-4b89-87a0-57990c5662dd)

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test again

**Comment by QiJin-Bouvet** [comment]
Tested with commit 47aa895 in TEST env.
Low and high estimate time is calculated correctly.

We will discuss how to calculate sum time in the scenario 'choice card with loop' in the status meeting tomorrow.
Currently the loop is been ignored.
