### ISSUE TITLE
Feat: Full name of users

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#197]
**User story**
As I user I want to relate to full names throughout the Flyt-app, so that I don't need to remember/look up short names separately. I also want to be able to use short names when I know them, so that I don't have to look up full names separately. In addition, it should only be possible to add existing Equinor users (user name in AD).

**User input 1 (by AMBB - Sharepoint ID89)**
Very nice app. As a user it would be good to see full name in sharing popup - not just short name.

**User input 2 (by HF - Sharepoint ID100)**
Hi, sharing the VSM with others is very good, but having to use only the shortname to put in the ones you want to share with makes it slower than necessary. is it possible to have that function based on both shortnames and names?

**User input 3(by JF - Sharepoint ID127)**
Love the tool, if it were capable of searching for a short name like you do when forwarding a document in M365 that would be great. Right now, I go to outlook to look up the short name and then send. Not a huge deal, but would be more efficient, if possible. Thanks again!

Relates to #148 

**Requirements**

~~#596~~ 
- [x] share user access using Equinor shortname
- [x] share user access using person's full name
- [x] when sharing: Should not be able to share with users that does not exist
- [x] when typing: suggest matches on short and full name. Applicable for both sharing rights pop-up and filter by user.
- [x] show full name. Applicable for sharing rights pop-up.
- [x] show full name. Applicable for title drop-down menu.
- [x] show full name. Applicable for filter by user on landing page.
- [x] show full name. Applicable for hover over user icon on process card on landing page.

**Link to figmafiles**

- [Share VSM access from landingpage](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5002-85536&mode=design&t=mLDjAhLuOZYVtmNL-4)
- [Share VSM access without rights from landingpage](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5002-85970&mode=design&t=mLDjAhLuOZYVtmNL-4)
- [Filter by user](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=4723-134698&mode=design&t=mLDjAhLuOZYVtmNL-4)
- [Check ownership](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5005-86309&mode=design&t=mLDjAhLuOZYVtmNL-4)
- [Share VSM access from canvas](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=4994-81907&mode=design&t=mLDjAhLuOZYVtmNL-4)
- [Share VSM access without rights from canvas](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5002-83537&mode=design&t=mLDjAhLuOZYVtmNL-4)

**Comment by SjoenH** [comment]
@Magos let's have a chat about this.

**Comment by SjoenH** [comment]
@Magos Let's schedule a time for talking about this.

Investigate how to get access to full-names (and emails?)
Also, today we use Short names… what will be affected by this change?

This feature should probably cover the input-field with search selections (like the add label input).

**Comment by knudsvik** [comment]
@SjoenH Another feedback on same issue (#362 ), a bit uncertain how to deal with similar issues in GitHub. Need to keep track of the input so that each initiator gets feedback when it's solved.

**Comment by knudsvik** [comment]
@SjoenH @Magos : Requirements OK?

**Comment by nesadrian** [comment]
Blocked until #703 is completed

**Comment by nesadrian** [comment]
Search functionality has been implemented. Waiting for get userAccess endpoints in #703

**Comment by nesadrian** [comment]
[Waiting on clarification](https://github.com/equinor/flyt/issues/703#issuecomment-2188318606)

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit d72f676 in Test env.
* show process users with full name in tooltips in Home page, works fine
* show process user with full name in user access popup in Home page, works fine
* share process with user by full name, works fine
* share process with user by shortname, works fine

Things need discuss or more work:
* check with @VetleW whether show created date in title dropdown menu, as Figma design linked above
* implement user fullname/shortname search for 'filter by user' in Home page

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Full name of users should be available in the filter page and the issues that caused some crashes should be fixed.

**Comment by nesadrian** [comment]
Blocked until we have implemented shortname user filter search in #703

**Comment by nesadrian** [comment]
This feature solves #199

**Comment by sir-larsen** [comment]
User filter by both shortname and full name available at /UserSearchByUsernameAndFullName

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Changes since last test is that users can now also be found by shortname in the user filter.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 09494dd in TEST env.
User filter works fine by either shortname or full name.

![image](https://github.com/user-attachments/assets/03b74086-b56f-42d0-883d-5ff9396ac7b9)
