### ISSUE TITLE
Decimal numbers in duration throws error

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#230]
**User input**
Duration hours gives 400 error when not supplying it with a whole number

**Sharepoint list ID**
90

**Comment by SjoenH** [comment]
**Suggested solution:** 
Do not allow decimal numbers for the input.

If we are to support decimals, then we probably need some changes to the API.

**Comment by SjoenH** [comment]
@Magos Would you take a quick look at how we are storing this value in the db?

**Comment by Magos** [comment]
The field storing duration is currently a 4-byte `int`, with range -2^31 (-2,147,483,648) to 2^31-1 (2,147,483,647).

**Comment by SjoenH** [comment]
And if I remember correctly, our base unit is in seconds? @pagodo

**Comment by Magos** [comment]
These ints are interpreted as minutes, actually, giving us a range of task durations up to 4083 years or ~150 generations.

**Comment by KaterynaBasik** [comment]
@QiJin-Bouvet could you please check if it's still an issue?

**Comment by QiJin-Bouvet** [comment]
@KaterynaBasik Yes, this is still reproducible in TEST, QA and Prod.

**Comment by HavardNot** [comment]
ready for test in test.flyt.equinor.com @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
The duration accept decimal number now.

![Image](https://github.com/equinor/flyt/assets/88656616/8004e617-ee3c-460b-88f1-f0e8409ea1c1)
