### ISSUE TITLE
Poor readability of text

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#248]
**User input 1 (by Karen-Maria Andersson - Sharepoint ID21)**
Still poor readability of text. Need to zoom in too much to read. 

**User input 2 (by Liv Håøy - Sharepoint ID39)**
Difficult to take picure of VSM - want to share VSM in presentation

**User input 3 (by Lise Storhaug Ekeland, Geir Lea Berge, Henriette Eidsnes)**
Vanskelig å print ut - screen shots - Tekst på SIPOC viser dårlig og skrift veldig liten. Vanskeliggjør visualisering og kommunikasjon.

**User input 4 (by Hans Kristian Vea- sharepoint ID180):**
Observation: 
Text / picture not rendering good when screen is shared via Teams 
( pixels lost? )

**Comment by SjoenH** [comment]
Does this concern all text, or just the text in the canvas?

**Comment by SjoenH** [comment]
Might be improved by baking the Equinor font into a high-resolution `BitmapText font`. Ref https://github.com/pixijs/pixijs/issues/4939#issuecomment-392565787
