### ISSUE TITLE
Feat: Hover text for long text in cards

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#253]
**User input 1 (by Lise SE, GLB, HE):**
Liten plass til tekst – kun deler viser av både header og undertekst 

**User story**
As a user I want to know the full text of a card when hovering the mouse over so that I don't have to open the sidebar every time a card has more 

**Describe the solution you'd like**
Mouse hover-over text when length of text is extending the limitations

**Comment by VetleW** [comment]
[New design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5823-65209&mode=design&t=WHRbkhkCIFnErGLB-4)
text shold only show when the user hovers over the text, not the add card buttons

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test in [TEST](https://test.flyt.equinor.com) environment.

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
When hover over a card, the tooltips shows the text of Description, Role, and Duration.

![image](https://github.com/equinor/flyt/assets/88656616/601ad5ba-b722-4a7e-8b61-37d248ae5eae)
