### ISSUE TITLE
URL aliases to Dev, Test and QA

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#280]
**User story**
As product owner and potentially user forum member I would like to find qa, test, dev environments easier so that I don't have to find the url's through GitHub

**Describe the solution you'd like**
qa.flyt.equinor.com --> https://web-vsm-qa.radix.equinor.com/
test.flyt.equinor.com --> https://web-vsm-test.radix.equinor.com/
dev.flyt.equinor.com --> https://web-vsm-dev.radix.equinor.com/
api.flyt.equinor.com --> vsm-api-prod.azurewebsites.net/swagger/
service.flyt.equinor.com --> https://web-mad-service-portal-web-prod.radix.equinor.com/Flyt

**Comment by SjoenH** [comment]
This is already available in the Readme: https://github.com/equinor/MAD-VSM-WEB#branching-and-deploying-stuff
Any suggestions on where would be a better place?

| Environment | Release script          | Deploy status                                                                                                                  | URL                                     | Who should test what?       | Comments                                                                         |
| ----------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------- | --------------------------- | -------------------------------------------------------------------------------- |
| DEV         | Run `yarn release-dev`  | ![DEV environment build status in Radix](https://api.radix.equinor.com/api/v1/applications/vsm/environments/dev/buildstatus)   | https://web-vsm-dev.radix.equinor.com/  | Developer                   | Developer is free to use this environment however they want to                   |
| TEST        | Run `yarn release-test` | ![TEST environment build status in Radix](https://api.radix.equinor.com/api/v1/applications/vsm/environments/test/buildstatus) | https://web-vsm-test.radix.equinor.com/ | Internal testing            | Developer tags what needs to be tested for QA-tester in the team                 |
| QA          | Run `yarn release-qa`   | ![QA environment build status in Radix](https://api.radix.equinor.com/api/v1/applications/vsm/environments/qa/buildstatus)     | https://web-vsm-qa.radix.equinor.com/   | "Product Owner" or Customer | When said feature is ready, it gets released into QA, so our PO can give feedback |
| PROD        | Run `yarn release-prod` | ![PROD environment build status in Radix](https://api.radix.equinor.com/api/v1/applications/vsm/environments/prod/buildstatus) | https://web-vsm-prod.radix.equinor.com/ | End-users                   | We wait with deploying to prod until everyone is happy                           |

**Comment by SjoenH** [comment]
Ah, I see what you mean now. Adding either redirects or subdomains on the Flyt domain..

**Comment by knudsvik** [comment]
@SjoenH Is this something relatively easy to fix? Don't like to always having to go to github to find the addresses to the other environments, feel this could be good for all of us?

**Comment by SjoenH** [comment]
If we want proper sub-domains, we would need to order them ( doesn't take too much time, usually @StaaleW fixes it for us ) but not sure what the policy to get domains for test environments are. 🤔 

We would also need to order certificates for the new sub-domains and configure them.

Maybe a redirect on the domain is better? Then we don't need any new certificates... 
That could be done in the domain registration or in the app itself.
@StaaleW do you have any input?

If we do a redirect in the app code, the URL form would look a bit different:

- `flyt.equinor.com/dev` 👉  `https://web-vsm-dev.radix.equinor.com/`

- `flyt.equinor.com/test` 👉 `https://web-vsm-test.radix.equinor.com/`

- `flyt.equinor.com/qa` 👉 `https://web-vsm-qa.radix.equinor.com/`

**Comment by knudsvik** [comment]
If we are going for sub-domains (i think I prefer this, more in line with other Equinor apps) we should maybe think about the API as well?  @Magos ?
`vsm-api-prod.azurewebsites.net/swagger/` 👉`api.flyt.equinor.com` ?

**Comment by nesadrian** [comment]
@SayyareHamit You should be able to access Flyt 1.0 environments by using the following URL's now: 

https://dev.flyt.equinor.com 👉 https://web-vsm-dev.radix.equinor.com/

https://test.flyt.equinor.com 👉 https://web-vsm-test.radix.equinor.com/

https://qa.flyt.equinor.com 👉 https://web-vsm-qa.radix.equinor.com/

The QA environment is not up and running at the moment so you will not be able to load any processes. Custom domain for the api and service portal is trickier to set up and will be put on hold

**Comment by SayyareHamit** [comment]
I am able to access ALL these environments by using the URL's above. @nesadrian 😎
