### ISSUE TITLE
Infinite scroll on front page

### ISSUE THREAD

**Issue by SjoenH** [equinor/flyt#312]
@knudsvik suggested using an infinite scroll instead. And I agree.

_Originally posted by @SjoenH in https://github.com/equinor/MAD-VSM-WEB/issues/218#issuecomment-981459283_

**Comment by HavardNot** [comment]
ready for test in https://test.flyt.equinor.com/ @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested with commit 239524f in TEST environment.
Homepage loads all processes by scrolling down. 
No page navigator anymore.

![image](https://github.com/user-attachments/assets/487184d2-67af-43bb-a15c-46f486cc04c6)
