### ISSUE TITLE
Navigate on canvas with keyboard arrows

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#320]
**User input 1 (by ZC- Sharepoint ID110)**
for the user, it will be nice to be able to scroll down

**User input 2 (by Lise SE, GLB, HE)**
Sensitivt mht å bla vertikalt – fort gjort å forskyve bokser - => egen scrolle knapp ?

**User story**
As a user I want to use an alternative way to the mouse to navigate in the canvas so that it works with my intuition

**Possible solution**
Move around the canvas using the keyboard arrows

**Comment by SjoenH** [comment]
Need more information about what the user is trying to do.

**Comment by knudsvik** [comment]
Issues are probably related. Same user.
- #319
- #320 
- #321

**Comment by knudsvik** [comment]
Additional user input: This to be able to quickly access the lower part of the process.  The application is quite slow and dragging up was taking forever, therefore if there is a scroll down possibility, it might be faster to reach the lower part of the page without zoom in and out.

**Comment by SjoenH** [comment]
Yes, probably connected to the #319.
