### ISSUE TITLE
Bad performance while showing a process

### ISSUE THREAD

**Issue by SjoenH** [equinor/flyt#385]

**Comment by SjoenH** [comment]
@knudsvik 👋 
Would you help me fill out the details around the performance issues you are experiencing?

- [ ] Machine and setup.
- [ ] Browser
- [ ] What do you do to trigger it?
- [ ] What other software is in use -> Teams, Virus scan etc... 📹 
- [ ] etc.

**Comment by knudsvik** [comment]
> * [x]  Machine and setup: HP EliteBook x360 G3 - varying screens. Usually internal + 2*24". New desk: internal + 2x30"
> * [x]  Browser: Edge 99.0.1150.52
> * [x]  What do you do to trigger it?: Opening the sidepanel is often not possible.
> * [x]  What other software is in use -> Teams, Virus scan etc... 📹: Teams meeting (sharing screen)
> * [ ]  etc.

**Comment by ofredstie** [comment]
I would argue that this is a feature improvement, not a bug. Being slow is not the same as being broken. Please consider removing the "Bug" label.

**Comment by askbulle** [comment]
Related to #446
