### ISSUE TITLE
Intuitive renaming of a process

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#417]
**User input 1 (by FL- sharepoint ID145):**
As a user of Flyt I would like to be able to rename the process mapping by selecting the name of the process mapping instead of using the dropdown menu.

**Describe the solution you'd like**
Click on name of process to rename it.

**Requirements**
- [x] Click on name of process one has Owner/Admin/Contributor access to allows renaming
- [x] For those without write access nothing should happen when clicking name of process
- [x] Auto-save new name without pressing Enter (like other entering of text in Flyt)
- [x] Pressing Enter moves cursor out of the title bar
- [x] Keep rename option in drop-down menu (with Duplicate and Delete)
- [x] Rename option in drop-down menu should still work (keep existing functionality)

**Comment by nesadrian** [comment]
@knudsvik I'm done with this but I'm thinking that it might be confusing for existing users and people who are not used to click to edit functionality if we remove the rename option from the dropdown menu. We could alternatively have both options available. What do you think?

**Comment by nesadrian** [comment]
@askbulle @knudsvik Live in Test now 👍

**Comment by nesadrian** [comment]
Sounds good! In code review now. I also added a loader for when the title is loading. Previously it said "Untitled process", which was a bit misleading.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test in [TEST](https://test.flyt.equinor.com/)

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
Process name can be changed either from the dropdown menu or by clicking the text directly.

![Image](https://github.com/equinor/flyt/assets/88656616/caf20e89-e788-40d6-8ecf-6f13aa635cd6)

**Comment by nesadrian** [comment]
The font has been changed and I have added space between the text and the box highlight.
This is ready for testing.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 3b43d0a in TEST env
- The title text could be a bit bigger as in Prod
- The menu beside process title doesn't disappear by clicking outside the menu

![Image](https://github.com/equinor/flyt/assets/88656616/8c9ce061-7f80-4397-8a2c-ac63054914ce)

**Comment by nesadrian** [comment]
I have changed the font size, but the menu not disappearing seems to be a problem that exists on the main branch and is not related to these changes

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
The font size is 20px now.
