### ISSUE TITLE
Feat: Links in PQIR's

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#436]
**User story**
As a user I want to add links in problems, ideas, questions and risks so that the functionality is coherent throughout the application.

**User input 1 (by Thorjan Knudsvik- sharepoint ID170):**
Not possible to add links properly to PQIR's like the activity boxes. pasting regular links creates visualisation issues in the categorisation page.

**Describe the solution you'd like**
Markdown links as in the cards. 

**Relevant issues**
#432

**Comment by VetleW** [comment]
[new design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5823-65004&mode=design&t=WHRbkhkCIFnErGLB-4)

**Comment by HavardNot** [comment]
ready for test in https://web-flyt-dev.radix.equinor.com/ @QiJin-Bouvet

**Comment by HavardNot** [comment]
ready for test in https://web-flyt-dev.radix.equinor.com/ @QiJin-Bouvet

**Comment by HavardNot** [comment]
ready for test in https://web-flyt-test.radix.equinor.com/ @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
* able to add links when creating a link
* able to add links to an existing PQIR
* Links are shown in category page

![image](https://github.com/equinor/flyt/assets/88656616/b4dac349-79c9-44ea-9c9a-55771394444c)

![image](https://github.com/equinor/flyt/assets/88656616/51eae976-ad9a-4f5b-85ba-0646d61cea77)
