### ISSUE TITLE
Visualise links in canvas

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#437]
**User input 1 (by Fredrik Liknes- sharepoint ID165):**
As a user of Flyt I would like to have my hyperlinks visible (underlined, sharper etc..) on the cards when looking at the VSM to highlight that there are navigation options within the cards.

**User input 2 (by Lise Storhaug Ekeland, Geir Lea Berge, Henriette Eidsnes)**
Mulig å linke inn fra andre kilder eller legge document direkte inn I FLYT? Er mulig- men tittel doc viser I boksen => lage eget felt og tegn for link som også viser i blå / gul boks? 

**User story**
As a user I want to know if an activity box contains links so that I know more information is available

**Describe the solution you'd like**
Visual cue for links, either in the link text or as an icon on the card.

**Comment by VetleW** [comment]
[new design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5823-65052&mode=design&t=WHRbkhkCIFnErGLB-4)

**Comment by nesadrian** [comment]
Link should also be visible in the tooltip

**Comment by HavardNot** [comment]
https://web-flyt-test.radix.equinor.com/
