### ISSUE TITLE
Enable writing directly on cards

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#445]
**User input 1 (by Marius Hegdal- sharepoint ID167):**
Enjoy using flyt for VSM first time today. 

Many neat functionalities, but I'd like to suggest a few improvements: 

- enable writing directly in the blue/yellow boxes, not having to go up in the editing field popping up on the right
- enable keyboard shortcuts for creating the different cards
- enable possibilities to copy/paste cards
- enable role and time input on main activity, not only sub activity

Best regards, 

Marius

**Comment by nesadrian** [comment]
When clicking on a text field on a card like description, role and time, the user will be able to start writing and the changes being made will also be displayed in the tooltip.

**Comment by tormodAase** [comment]
This is in code review now. There are some issues with this implementation, but I'm not sure how perfect we expect this implementation to be. The issues i've found:

- When using the arrow up/down to adjust duration, it will continue to increment/decrease the number indefinitely
- click and drag to select text does not work. Instead you move the canvas around

**Comment by tormodAase** [comment]
The above has been fixed, along with a lot of other stuff. In code review now

**Comment by tormodAase** [comment]
@QiJin-Bouvet Ready to test in the TEST environment!

**Comment by QiJin-Bouvet** [comment]
Tested with commit e20a63f in TEST.
When hovering over a card and try to add a new card, it open the editing window firstly, then show the newly added card.
It will be nice to fix it, although it doesn't break any function.

**Comment by nesadrian** [comment]
@tormodAase We had a discussion in todays meeting about this feature. can you take a look at how much work it is to make the tooltip be displayed beneath instead of above the card when the tooltip overflows the top of the canvas so that it is not hidden. The issue mentioned by Qi above should also be fixed before release.

**Comment by tormodAase** [comment]
@nesadrian @QiJin-Bouvet I haven't found any React Flow functionality to change the position of the tooltip automatically. It looks like we would have to create our own algorithm for that, which could take some time.

Looking into the issue Qi found right now

**Comment by nesadrian** [comment]
@tormodAase I did something similar to the contextmenu. In the isReversedExpansionDirection function i calculate if there is an overflow by using refs. Maybe we can do the same thing here.

**Comment by tormodAase** [comment]
@nesadrian lets have a talk about this today or tomorrow!

@QiJin-Bouvet a new version should be available in the test environment in a few minutes that should fix the issue you found!

**Comment by QiJin-Bouvet** [comment]
FYI, issue #834 is created for moving tooltips/edit boxes below the cards.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 53f4460 in TEST.
Writing directly on cards works fine.

**Comment by luan-droid** [comment]
enable role and time input on main activity, not only sub activity -  this issue is address in the ticket number #161 
enable keyboard shortcuts for creating the different cards - this issue is address in the ticket number #320

**Comment by luan-droid** [comment]
As discussed with Karen, 

**Enable keyboard shortcuts for creating different cards** – This feature is already implemented. You can hover over a card to copy and paste it.

**Enable role and time input on the main activity, not just the sub-activity** – Put this on hold for now, as we may need more feedback from users first.

**Comment by SIVN1** [comment]
Verified in Prod. Works fine

<img width="943" alt="Image" src="https://github.com/user-attachments/assets/72a0a72e-9fda-4e19-b53e-8a33f1e03440" />

CC: @AnjaliPandit20 @luan-droid @ThomasBracho1987
