### ISSUE TITLE
Hover the PQIR's to read the content

### ISSUE THREAD

**Issue by knudsvik** [equinor/flyt#449]
**User input 1 (by Fredrik Liknes- sharepoint ID169):**
As a user of flyt I would like to have a tooltip that displays the PQIRs when I hover over the icons.

**User input 2 (by Lise Storhaug Ekeland, Geir Lea Berge, Henriette Eidsnes):**
Når en går inn på et eksisterende problem – så viser ikke alt i bildet. Noe av teksten blir ikke synlig før vi trykker inne i boksen……………….Tror mange ganger at vi ikke har fått med det vi skal….

**Comment by VetleW** [comment]
[New design](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5823-65265&mode=design&t=WHRbkhkCIFnErGLB-4)

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test in [TEST](https://test.flyt.equinor.com/) environment.
