### ISSUE TITLE
Use the new Equinor CDN

### ISSUE THREAD

**Issue by dansvend** [equinor/flyt#534]
Switch to using the new Equinor CDN for the Equinor font because the old one i getting removed.

### Old
```
https://eds-static.equinor.com/font/equinor-font.css
```

### New
```
https://cdn.eds.equinor.com/font/equinor-font.css
```

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | Web        |
| Environment  | Test       |
| Version      | 0.2.26      |
| Commit       | 895ca36    |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good, here is screenshot of changing. @dansvend  ✨
![image](https://user-images.githubusercontent.com/128059194/236775416-18fb7b56-f8f5-4f66-b354-df414ac6701a.png)

**Comment by dansvend** [comment]
Thanks for testing @SayyareHamit 🙏 Moving issue to `🚦 Pending release`.
