### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by SayyareHamit** [equinor/flyt#584]
When I moving labels between main activities, these SubActivity acting weird. 

![Image](https://github.com/equinor/flyt/assets/128059194/df32aa46-83c9-40f2-8aa5-94d32ef5be5e)

![Image](https://github.com/equinor/flyt/assets/128059194/fc50004a-9d47-4e3f-9e45-72dfe95a921c)

**Comment by dansvend** [comment]
Fixed in #446
