### ISSUE TITLE
Option to include all children when deleting a card

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#588]
When a user selects a card and clicks the delete button I think we should include a checkbox inside the confirmation pop-up. This checkbox can be toggled to not only delete the selected card but also all of the cards beneath it in the tree.

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for TEST

**Comment by QiJin-Bouvet** [comment]
Tested with commit 8a516c1 in TEST env.
User can delete either only the selected card or the card together with its children.

![image](https://github.com/user-attachments/assets/b7d34a7e-258e-4bfe-b84f-9f05a7764872)
