### ISSUE TITLE
User access endpoints are only in V1

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#593]
If v1 endpoints are being removed then we need these endpoints in v2 aswell

**Comment by nesadrian** [comment]
@QiJin-Bouvet You can find the V2 endpoints [here](https://api-flyt-api-dev.radix.equinor.com/swagger/index.html?urls.primaryName=Flyt%20Api%20V2)

**Comment by QiJin-Bouvet** [comment]
User Accesses endpoints are available in flyt api 2.0
