### ISSUE TITLE
Canvas Tutorial

### ISSUE THREAD

**Issue by dansvend** [equinor/flyt#595]
**User story**
As a user of Flyt I want the latest changes to be presented to me in a good way. I also want to be able to revisit these changes at any time.

**Describe the solution you'd like**
When I launch Flyt I would like a modal to pop up with a title "What's new?" or something similar and to display me the relevant changes in the newest version for end users. It would be nice with some GIFs and easy to understand description. There should be a button in the right section of the top bar which will display modal again if I accidentally exited out of the modal or forgot what was in the release notes.

Related to [Information/Tutorial for new features#196](https://github.com/equinor/flyt/issues/196)

**Comment by dansvend** [comment]
> [Here](https://www.figma.com/file/SacZjN10goX2lahJrmjWC0/Flyt--%3E-Ideation?type=design&node-id=475-102961&mode=design&t=QhMn76u015NCibO6-4) is the first drat for a what's new pop up.

This looks nice! Awesome work 🔥

**Comment by VetleW** [comment]
Any feedback on [this](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5124-59967&mode=design&t=gAoqSEjlMAfK8qGI-4)? @dansvend

**Comment by dansvend** [comment]
> Any feedback on [this](https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?type=design&node-id=5124-59967&mode=design&t=gAoqSEjlMAfK8qGI-4)? Frame nr2 er prototypet og scrollbar. @dansvend

This looks really good 🔥  Any of them would work, but I might like option number 2 better 👌
