### ISSUE TITLE
Wong order when adding main activity

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#617]
Sometimes when adding a main activity card the id is added to the end of the root's children array instead of being added beside the id of the already existing main activity card like in the screenshot below

![Image](https://github.com/equinor/flyt/assets/35768833/0a9e4c7a-6f96-4e07-8c3f-cf2d53b21ced)

**Comment by anheri** [comment]
hard to recreate bug... leave it in backlog until it resurfaces again
