### ISSUE TITLE
Feat: Deletable edges

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#621]
The user should be able to delete edges between nodes.
Removeable lines are only found above a subactivity that has multiple parent connections.

**Comment by nesadrian** [comment]
Blocked until #185 passes QA

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test. Testing this functionality will also test #724

**Comment by QiJin-Bouvet** [comment]
Tested with commit 93543b2 in TEST env.
Delete edges for cards with multiple parents works as expected.
Tutorial updated for write on lines and delete lines.

![Image](https://github.com/equinor/flyt/assets/88656616/af614f70-d27c-486d-8094-15b8a5f36690)

![Image](https://github.com/equinor/flyt/assets/88656616/9db45732-41a6-45ce-8283-4c9d62a2c675)

![Image](https://github.com/equinor/flyt/assets/88656616/b76f31e5-7add-4aab-9fd4-380f1869bfe5)
