### ISSUE TITLE
Hide empty role and time containers on cards

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#631]
**User story**
I want to see as much information on cards as possible without opening the sidebar

**Describe the solution you'd like**
Hide role and time containers that are empty to make space for more description text

**Describe alternatives you've considered**

**Additional context**

**Development checklist**

- [ ] [Threat Modeling](https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html)

**Comment by KaterynaBasik** [comment]
Guessing, this is implemented in #449 and #253. Right @nesadrian ?

**Comment by nesadrian** [comment]
Yes, I would say that fixed this issue
