### ISSUE TITLE
Patch vulnerability

### ISSUE THREAD

**Issue by dansvend** [equinor/flyt#633]

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 The upgraded package is responsible for handling network requests. So you should test that changes to a process is working correctly.

```
---------------------------
| Platform     | Web      |
| Environment  | Test     |
| Version      | 0.2.33   |
| Commit       | 6efbd87  |
---------------------------
```

**Comment by SayyareHamit** [comment]
Works good in Test environment. @dansvend ✨

**Comment by dansvend** [comment]
Thanks for testing @SayyareHamit 🙏
