### ISSUE TITLE
To display a better error message

### ISSUE THREAD

**Issue by SayyareHamit** [equinor/flyt#643]
### **What happened**
When a user deleted a existing process, and kept the duplicate one. Than search the deleted process, the page should display a better error message than display status code 404. 

### **Steps to reproduce**
1. Click drop down list on a existing process and than click "Duplicate", then duplicate a process
2. Delete the original process
3.  Search the original process, than the page display an error message with status code 404
![image](https://github.com/equinor/flyt/assets/128059194/d7f9c873-09d4-433d-9fa2-fdbc22d07555)

### **Expected results**
The deleted process page should display a better error message, For example, This page has been deleted. 

### **Actual results**
The deleted process page display a message with status code 404

**Comment by nesadrian** [comment]
We should send an error message from the backend when a users try to access a process that do not exists

**Comment by HavardNot** [comment]
As there are no suggestions made for the improved error message I implemented a simple statement: ```C#
$"Unable to find project id: {query.Id}"
```

**Comment by HavardNot** [comment]
![Image](https://github.com/equinor/flyt/assets/110901733/51a9ba7f-4d01-42b2-8bca-59fd52e347a8)

**Comment by HavardNot** [comment]
ready for test in test.flyt.equinor.com

**Comment by HavardNot** [comment]
ready for test in test.flyt.equinor.com  use link to a deleted process to view the error message, e.g. https://test.flyt.equinor.com/process/514
@QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested with commit 65a96ea in TEST env.
Error message shown as below when process not found.
![image](https://github.com/user-attachments/assets/623073b9-92c8-4bf6-894f-11feba097a20)
