### ISSUE TITLE
Unable to delete process

### ISSUE THREAD

**Issue by SayyareHamit** [equinor/flyt#647]
### **What Happened?** 
Not able to delete a duplicated process. (2350)
![image](https://github.com/equinor/flyt/assets/128059194/b721dfbe-1ee7-4abe-9f67-8914e02f7668)

![image_720](https://github.com/equinor/flyt/assets/128059194/b30881ca-e7e0-45bd-bf6a-d6d9a0436593)

**### Steps to reproduce**
1. Duplicate a existing process
2. Click the dropdown button on top and click "Delete process"

**### Expected result**
The owner or the user have admin roll should be able to delete the process without any problem or error message

**### Actual result**
The owner of the process or the user have admin roll get the error message above when delete a duplicated process.

**Comment by anheri** [comment]
cant reproduce

**Comment by anheri** [comment]
this looks to be an isolotated problem to process 2350 alone
