### ISSUE TITLE
Patch vulnerabilities

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#651]
- Upgrade axios from 1.6.1 to 1.6.3
- Upgrade babel-core from 7.23.2 to 7.23.7

**Comment by nesadrian** [comment]
@SayyareHamit This is ready for test in [https://test.flyt.equinor.com/](https://test.flyt.equinor.com/) (Flyt 1.0 QA environment is currently down)

**Comment by SayyareHamit** [comment]
The features mentioned below are not included when duplicating a process in https://test.flyt.equinor.com/   @nesadrian 

Problems
Questions
Ideas
Write access/sharing rights
To-be process
Categories
Roles 
Durations

**Comment by nesadrian** [comment]
@SayyareHamit Is this related to #653 ? This patch is only for Flyt 1.0 so the fixes in Flyt 2.0 is not implemented here yet

**Comment by SayyareHamit** [comment]
Is this correct version of environment? @nesadrian 
![image](https://github.com/equinor/flyt/assets/128059194/bdb7c420-01bf-4259-b0b6-7b9e57905858)

**Comment by nesadrian** [comment]
Yes, commit c499832 is correct 👍

**Comment by SayyareHamit** [comment]
Oki, I got it. Than this is good to go. @nesadrian ✔
