### ISSUE TITLE
The search page has wrong sorting

### ISSUE THREAD

**Issue by SayyareHamit** [equinor/flyt#655]
This process should not appear on the first page when the modified date is older than other processes.

**(The screenshot is taken of the QA environment)**
![Image](https://github.com/equinor/flyt/assets/128059194/5ad9dc90-3b36-4e4e-afed-9261a4b77241)

**Comment by anheri** [comment]
this is also a problem in production. Are we fixing that as part of this release

**Comment by KaterynaBasik** [comment]
We are not fixing that as part of this release. 
But I can reproduce this in prod as well

**Comment by QiJin-Bouvet** [comment]
Tested with commit adf3362 in TEST env.
The sorting looks correct as Last modified.

![Image](https://github.com/equinor/flyt/assets/88656616/3f257ff3-d3c8-49d8-ba81-85ff21831b0c)

**Comment by QiJin-Bouvet** [comment]
Tested in QA env. Works good.
