### ISSUE TITLE
Error handling for the empty PQIR's description

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/flyt#667]
**Describe the bug**
In the current version, it is possible to delete a PQIR's description and keep it empty. And in this case, such PQIR won't appear in a new version (for example, P23 in the process 2106).
In a new version, deleting all the text from the description files is impossible - it gives a service message `Request failed with status code 400`.  But it might be good to implement a better error message.

BTW is there any reason to keep PQIR  with no description?

**Comment by nesadrian** [comment]
I have made this so far. The text field is not an EDS component, but I have used EDS colors and fonts. Any feedback on the design @VetleW?

![Image](https://github.com/equinor/flyt/assets/35768833/3883eca0-1fa9-4aea-83bd-3a21126ebc3d)

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit 053623a in TEST env.
Empty description field for PQIR is not allowed.
