### ISSUE TITLE
Fix TypeScript strict mode errors

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#668]
TypeScript strict mode should be set to true to improve the development process and code quality. Flyt was developed without strict mode and there is a lot of errors to fix.

**Comment by HavardNot** [comment]
ready for test in test.flyt.equinor.com @QiJin-Bouvet 
This is a non-functional change that affects almost all parts of the app. Will need a thorough regression test analysis to ensure nothing has been broken or changed for the worse.

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env with commit 5cf774e.
The PQIR cards turn grey when adding/removing a category to it.
Refresh page fix it.
This problem doesn't happen in QA env.

**Comment by QiJin-Bouvet** [comment]
Tested in Test env with commit be367ea
PQIR cards are not grey when add/remove category on them.

**Comment by nesadrian** [comment]
@HavardNot @QiJin-Bouvet I think these changes has introduced a bug where the project menu scrim can't be closed. The bug exists on the main branch but not in QA, and these changes are the only ones that are not built to QA.

![Image](https://github.com/equinor/flyt/assets/35768833/c4f57221-0eea-477c-95f9-70507557490c)

**Comment by QiJin-Bouvet** [comment]
@HavardNot Could you take a look and make a fix for it?

**Comment by HavardNot** [comment]
ready for test in test.flyt.equinor.com @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested with commit 17b9663 in TEST env.
The menu works as expected.

**Comment by QiJin-Bouvet** [comment]
Tested in QA env.
Works fine.
