### ISSUE TITLE
Allow "0" duration on cards

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#671]
When duration is set to "0", duration and time unit should be displayed on the card.

**Comment by SayyareHamit** [comment]
Not able to see the duration and time unit when duration is set on "0". @nesadrian 
![image](https://github.com/equinor/flyt/assets/128059194/a83ac12b-f947-45e2-82b8-5fb65ff792db)

**Comment by nesadrian** [comment]
@SayyareHamit This is ready for test in [TEST](https://test.flyt.equinor.com/ ) env now

**Comment by nesadrian** [comment]
You can move this to pending release if the test passes

**Comment by QiJin-Bouvet** [comment]
Works good in TEST env. @nesadrian
