### ISSUE TITLE
Better mapping solution for choice card options and its activity cards

### ISSUE THREAD

**Issue by QiJin-Bouvet** [equinor/flyt#678]
## Description

As a Product Owner, I want a more clear way to show the activity belongs to which option of a choice card.

![image](https://github.com/equinor/flyt/assets/88656616/6fd85337-c565-4301-b509-3f64dd4b11fe)

## What needs to be done:

- [ ] Discuss with PO to find a good solution, by card position or label on the lines?

When this is done, please do the following:

- [ ] Test a production build before release 
- [ ] UAT (provide access for the group of users)
- [ ] Release on a date that is agreed with the PO

### Design

- [ ] figure out how to implement the solution, front-end, back-end, technical challenges?

### Acceptance Criteria

- [ ] A solution is defined and implemented
- [ ] When there is only one activity card under choice card, it should be clear which option leads to the activity
- [ ] User can add more than two activities card under choice card, and each option to the activity should be clear 

### Definition of Done

- [] Acceptance criteria met
- [] Code has been reviewed
- [ ] Unit test(s) are created and passing
- [ ] Functional tests created and passing

**Comment by KaterynaBasik** [comment]
Does this requirement implemented in #185 ? Is this what you meant @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Yes, we don't need this issue anymore after the feature #185
