### ISSUE TITLE
Multiple children under sub activities and waiting cards

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#685]
**Describe the bug**
It's possible to add multiple children under sub activities and waiting card.

**To Reproduce**

1. Go to a process
2. Hover over a sub activity or waiting card
3. Click fast and multiple times on one of it's add card buttons

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. After clicking on a add new card button, that button group should be disabled until the card has been added. The merge button do not need to be disabled since merging won't interfere witch new cards being added.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 4a95ffd in TEST env.
No multiple child cards by clicking add button quickly.
