### ISSUE TITLE
Moving choices from loops to another column

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#690]
**Describe the bug**
If you move a choice that's within a loop to another column the choice's subtree will still have the connection to the top of the loop. This is an issue because cards should not be able to have connections to other columns.

**To Reproduce**

1. Go to a process
2. Add a sub activity card
3. Add a choice under the sub activity card
5. Merge one of the choice's children with the sub activity card
6. Move the choice to another column
7. See error

**Expected behavior**
The connection should either be removed or the whole loop should be moved.

**Screenshots**
![image](https://github.com/equinor/flyt/assets/35768833/1b0685ab-c0af-4dde-aae6-f536aa87f946)

**Comment by KaterynaBasik** [comment]
With the functionality implemented in #621 it's not actual any more
