### ISSUE TITLE
Not enough Pages for all processes

### ISSUE THREAD

**Issue by QiJin-Bouvet** [equinor/flyt#697]
Tested in https://flyt.equinor.com/
The flyt homepage only show **52** pages of processes.
There are 1930 processes in database, where 370 processes are for ToBe view, which won't show in Homepage list.
With 15 processes in each page, (1930-370)/15=104, it should be **104** pages. 

![Image](https://github.com/equinor/flyt/assets/88656616/44da59b2-fe57-4c5b-bca9-064dce1af017)

**Comment by QiJin-Bouvet** [comment]
According to wiki page:
> All processes are open to viewing, but the ones without a name has been filtered out in the "All processes" screen (usually the ones people make for testing purposes).

There are 771 processes without a name in database, and (1930-370-771)/15 = 52,6.
So it should be 53 pages there.

**Comment by KaterynaBasik** [comment]
Can we close this issue?

**Comment by QiJin-Bouvet** [comment]
Yes. Issue closed.
