### ISSUE TITLE
Add users full names to useraccess endpoints

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#703]
In order to complete #197 we need to update the following endpoints to also include the full name of the user:
- All /useraccess GET endpoints
- /project GET endpont's useraccess property

**Comment by sir-larsen** [comment]
@nesadrian Full names now added with user creation in SQL database, as well as an endpoint to get users from graph API.

Endpoint:   /api/v2/users/query?startsWith={searchTerm}

Running in DEV.

Full names not yet returned in response UserAccess.

**Comment by nesadrian** [comment]
If we are going to include full names in the "Filter by user" box on the processes page then we need some additional work on the backend. At the moment we call this endpoint when searching: /userAccess/userSearch?q= The endpoint only retrieves users based on short name but should retrieve them based on short and full names. I will bring this up for discussion on the Thursday meeting.

**Comment by sir-larsen** [comment]
The search endpoint uses first name, last name and also short name as search parameters. So you can already do full name search.

![image](https://github.com/equinor/flyt/assets/76153505/82881b57-1a1d-46a2-a689-a824851e4498)
![image](https://github.com/equinor/flyt/assets/76153505/046eef8c-b324-4a95-9237-513b40b54caf)


![image](https://github.com/equinor/flyt/assets/76153505/0be7faaa-e694-4a16-8b10-816a9efe928e)
![image](https://github.com/equinor/flyt/assets/76153505/98bd4f85-329d-462b-910a-8c7d183a37a0)

**Comment by nesadrian** [comment]
The endpoint I'm referring to is different from the graph api search

**Comment by sir-larsen** [comment]
Full name user search running in dev and test.

Endpoint: /api/v2.0/userAccess/userSearchFullName?q={FullName}
