### ISSUE TITLE
fix: Truncate card description

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#717]
If the text in a card is overflowing we should truncate the text and use ellipsis to indicate that there is more text. There is a problem where a long role or duration text will cause the text to overflow the box, which should be fixed by this.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test in qa.flyt.equinor.com. Let me know if I need to clarify something.

**Comment by QiJin-Bouvet** [comment]
Tested in QA env.
Long text in cards is truncated.
![image](https://github.com/equinor/flyt/assets/88656616/caf93e9d-82ab-4c91-a07b-a895bf403d1d)
