### ISSUE TITLE
refactor: Graph endpoint

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#725]
Because of the changes made in #723 we need to change how the frontend handles edges. Previously we made the edges based on the node hierarchy, but now we will use the edges we get from the endpoint.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test in [https://test.flyt.equinor.com/](https://test.flyt.equinor.com/). Testing this will also be testing #726. This has been a comprehensive refactoring. Here is a list of what should be tested:
- [ ] User access box
- [ ] Clicking on project card and redirecting to canvas
- [ ] Updating card in sidebar
- [ ] Link task to category
- [ ] New task
- [ ] Create and open ToBe
- [ ] Get QIPR
- [ ] Update project name
- [ ] The biggest change affects all canvas functionality (Multiplayer, cards, merges and so on) (Tutorial and zooming does not need to be tested)

**Comment by QiJin-Bouvet** [comment]
@nesadrian 
Tested in TEST env.
There are several processes have empty canvas, eg. 487, 496, 490, 500 and more.

**Comment by nesadrian** [comment]
@QiJin-Bouvet If they were made a long time ago then it is because the test environment processes were never migrated from 1.0 to 2.0. To be sure I checked 487 in the new graph database and it does not have any data.

**Comment by QiJin-Bouvet** [comment]
Tested in TEST env.
Edges are received from backend when loading process.
No function broken.
