### ISSUE TITLE
feat: Show zoom value next to controls

### ISSUE THREAD

**Issue by HavardNot** [equinor/flyt#736]
Relates to #473 and new design template https://www.figma.com/design/IkHwmIQrsT0iR34f5R5UnZ

**Comment by HavardNot** [comment]
![image](https://github.com/equinor/flyt/assets/110901733/cf57e014-52a8-4057-9e83-8981203a04b6)

**Comment by HavardNot** [comment]
Ready for test in https://web-flyt-test.radix.equinor.com/ @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Need more clarification from PO. Will show it to PO on Thursday (6th June) and get feedbacks.

**Comment by QiJin-Bouvet** [comment]
PO approved. Ready to release.
