### ISSUE TITLE
Decommision VSM API endpoint in mad API Management

### ISSUE THREAD

**Issue by mglendrange** [equinor/flyt#748]
We trying to decommision the mad API Management service in good time before 31.08.24, ref https://github.com/equinor/mad-team/issues/444

Wondering if it is safe to delete the VSM API from the mad API Management service, or if we need to migrate the frontend to using the Radix API URL directly?

The APIM endpoint URL is https://api.statoil.com/app/vsm/prod, which is still referenced in this repo:
![image](https://github.com/equinor/flyt/assets/6025616/50d8defa-359f-4800-ad63-a2080af6b9d0)

APIM points toward the vsm-api-prod app service, which is still running and have had 108 requests in the last 30 days:
![image](https://github.com/equinor/flyt/assets/6025616/0642cf06-b813-4c09-bdd4-9f517fe4ca7b)

**Comment by mglendrange** [comment]
Had a discussion with Adrian about it. The APIM API endpoint is still used on a server running the old Flyt version. Kateryna/Adrian will check if/when the old Flyt version can be decommissioned, or if we need to migrate the front end to the app service URL instead

**Comment by KaterynaBasik** [comment]
Checked with the PO, the old Flyt version is needed to be running as for now. Will back to this discussion in August.

**Comment by KaterynaBasik** [comment]
We can start the VSM API endpoint decommissioning. It has been approved by the PO
