### ISSUE TITLE
Bug: Zoom level duplicated in top right

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#749]
The zoom level is also displayed in the top right of the canvas upside down.

![Image](https://github.com/equinor/flyt/assets/35768833/4f5ad544-e664-43a3-8aab-627da26be30b)

**Comment by HavardNot** [comment]
Ready for test in https://web-flyt-test.radix.equinor.com/ @QiJin-Bouvet

**Comment by QiJin-Bouvet** [comment]
Tested in QA env.
No upside-down zoom value in top right corner anymore.
