### ISSUE TITLE
SIPOC helper text

### ISSUE THREAD

**Issue by VetleW** [equinor/flyt#759]
Add describing helper text to greencards to guide users.

[Figma design](https://www.figma.com/design/IkHwmIQrsT0iR34f5R5UnZ/Flyt--%3E-Design?node-id=6023-75965&t=C1wxz5RXKQBLNHdT-4)

Supplier text:
4. Who or what supplies the Input? List the Supplier(s) (e.g. collaborators, data systems, plans, requirements)

Input text:
3. What triggers you to begin the process? List the Input(s), (eg. information, materials, tools, a weekly meeting etc)

Output text:
1. What are the key deliverables or results of the process? List the Output(s).

Customer text:
2. Which role or system recieves the Output? List the Customer(s).

**Comment by nesadrian** [comment]
@VetleW If I understand it correctly the helper text should be displayed when the card does not have any description. I think it would be nice to have the text permanently in the sidebar aswell. This way the user won't have to open an empty process or delete the description in order to see the helper text.

**Comment by nesadrian** [comment]
Should the card header color be changed to black like in the design? At the moment we have grey text for headers. The headers also disappears when a user adds a description to the card. The description text color is black.

![Image](https://github.com/equinor/flyt/assets/35768833/7616ee65-66a8-4243-af2b-7d42477e31ea)

**Comment by VetleW** [comment]
> @VetleW If I understand it correctly the helper text should be displayed when the card does not have any description. I think it would be nice to have the text permanently in the sidebar aswell. This way the user won't have to open an empty process or delete the description in order to see the helper text.

Totally agree! Would be nice to keep the text in the sidebar aswell.
And I do think the header should be more visible. Maybe it should still be visible even after users have written on the card?

**Comment by nesadrian** [comment]
It's definitely a possibility now that we have the card tooltip. We can discuss this further in the meeting.

**Comment by nesadrian** [comment]
As discussed in the meeting:
No green card description:
- Black header text
- Gray helper text
With green card description:
- Gray header text
- No helper text

**Comment by nesadrian** [comment]
@VetleW What do you think about this?

![Image](https://github.com/equinor/flyt/assets/35768833/8696b48e-f1c9-4b80-aaf8-12003bf140a2)

**Comment by VetleW** [comment]
Looks good to me, but could you check what it would look like just below the heading and above the inputfield?

**Comment by nesadrian** [comment]
I prefer the first alternative. This one feels a bit more cluttered to me.

![image](https://github.com/equinor/flyt/assets/35768833/db85f01f-30f9-42a9-953e-417dc006decd)

**Comment by nesadrian** [comment]
This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit 240c721
* Helper text shown in grey in green cards when there is no user input
* Text in black replace the helper text when user enter text

![Image](https://github.com/user-attachments/assets/4322a7de-f5e1-46fc-b085-64bfbc10f341)

![Image](https://github.com/user-attachments/assets/c23b7bad-83fe-4a3d-9bae-8410707171f6)
