### ISSUE TITLE
Suppress drag events when clicking a node

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#760]
If the users slightly moves the cursor when clicking a node it will not register as a click but a drag. A [new version](https://github.com/xyflow/xyflow/releases/tag/11.9.0) of reactflow has added support for changing the drag threshold which makes it possible to fix this issue.

**Comment by nesadrian** [comment]
After testing this it looks like the click handler still works the same. With these changes we do suppress the drag events during the click which will slightly improve performance, prevent potential bugs and it looks better.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Previously, clicking on a card would cause the website to act as if the card was being dragged. Cards that it could not be dragged on top of would darken for a second for example. Now the card has to be dragged for these events to happen.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 34912b1
Click and hold on a card won't make any other cards dark, work as expected.
