### ISSUE TITLE
fix search for PQIR & unit

### ISSUE THREAD

**Issue by VetleW** [equinor/flyt#762]
When adding unit or problem type, we use autocomplete. When we write something we filter out all non matching Items, I think we should sort, instead of filtering. Since there are so few options and since it is easy to write something wrong and then have no options.

![Image](https://github.com/equinor/flyt/assets/130735266/2ea9733f-d8ad-4736-993e-d0f407a52f74)
![Image](https://github.com/equinor/flyt/assets/130735266/89f493cc-5f67-42f1-b10c-0daa3b9a403b)
![Image](https://github.com/equinor/flyt/assets/130735266/98f047d3-2937-4527-b373-67aee1a19118)

Example of how sorting would work. All matching items will be above the divider, but all other choices are available as well. Same goes for choosing problem type in PQIRs.

![Image](https://github.com/equinor/flyt/assets/130735266/66c4b0f7-9720-423f-88ca-0dc3f15ff8e7)

**Comment by nesadrian** [comment]
I'll also increase the height of the dropdown list for selecting PQIR's so that we don't have to scroll to see the last two options.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. We dropped adding the gray line that you can see between Months and Hours in the design since it's not possible in EDS.
