### ISSUE TITLE
Patch vulnerabilities

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#765]

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test. It's a minor upgrade to our socket packages which affects the live collaboration feature.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 77be156 in TEST env.
Live function works good. 

![Image](https://github.com/equinor/flyt/assets/88656616/f7ed26b3-1be8-4b3a-8ef4-112dea3f3600)
