### ISSUE TITLE
Task: Update Flyt wiki page with new gif

### ISSUE THREAD

**Issue by QiJin-Bouvet** [equinor/flyt#769]
We need to maintain the Flyt wiki page to keep it up to date.
Especially some gif are needed:
* 'Toolbar for grouping and adding labels' section: show version history button is replaced by tutorial button
* Toolbar in the left bottom corner: mini map, fit view, zoom out, zoom in, zoom percentage

Please prepare the gif and check with Karen when and who does she want to update the wiki.

![Image](https://github.com/equinor/flyt/assets/88656616/2c2c25a7-9a65-496c-90de-08536cd661cd)

![Image](https://github.com/equinor/flyt/assets/88656616/a208ef4f-7bec-4ff2-8df9-93593eb8445c)

![Image](https://github.com/equinor/flyt/assets/88656616/64efdf1c-0860-45d0-ae15-88f15f76d9d7)

**Comment by VetleW** [comment]
Just created some gifs for now.

![Image](https://github.com/equinor/flyt/assets/130735266/7f8a1a77-1806-43bc-9cc1-06e668906156)



![Image](https://github.com/equinor/flyt/assets/130735266/3822371c-aeb9-4e3b-a2ad-0e4968965bb2)

**Comment by KaterynaBasik** [comment]
Updated now
