### ISSUE TITLE
Remove "old" flyt

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#785]
Since we are decomissioning the "old" flyt API we will also have to remove the "See process in Flyt 1.0" button.

**Comment by HavardNot** [comment]
Should we also create an issue for the backend as well? i guess there are a lot of endpoints that are "old" flyt exclusive

**Comment by nesadrian** [comment]
I think we made a backup of the flyt backend code before starting the migration and this is what the "old" flyt is running. I thought we cleaned up the code during migration, but after taking a look at it I see that there are a lot of code commented out in old endpoints. I'll make an issue for this.
