### ISSUE TITLE
Copy and paste cards

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#789]
Requirements:
- [x] Clicking command/ctrl + C while hovering a card, copies the card to the clipboard
- [x] Clicking command/ctrl + V while hovering a card will add the copied card as a child to this card
- [ ] All of the cards content, excluding PQIR, is copied
- [x] A snack message will notify the user that the card has been copied

Discuss:
- Should this feature be a part of the canvas tutorial. 
Answer: Yes  #793

**Comment by nesadrian** [comment]
As discussed in today's meeting choice cards will not copy it's children. Instead it will be pasted the same way new choice cards are made, but with the copied cards description. PQIR's will not be copied as this require a good amount of effort.

**Comment by nesadrian** [comment]
Blocked until #797 is merged

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit cddOf17 in TEST env.
Copy & paste cards works fine.
