### ISSUE TITLE
Add Copy/Paste info to Tutorial

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/flyt#793]
As a new feature https://github.com/equinor/flyt/issues/789  is about to be implemented it's important to let users know how to use it.
It's decided to add some information to Tutorial and to Wiki page

**Comment by VetleW** [comment]
Copy paste tutorial gif and video

![Image](https://github.com/user-attachments/assets/3e985d87-d7ee-4844-9089-986c488708b8)
https://github.com/user-attachments/assets/1f1ea896-399a-448b-acff-da16006f9711

**Comment by nesadrian** [comment]
Blocked: Waiting for #799 to pass testing before adding shortcut explanation to tutorial

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit 60dbe8e in TEST environment.
The tutorial looks good.
But there is a dashed line box around option 'Delete' when clicking Copy and Paste in the video.
