### ISSUE TITLE
Right-click menu

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#799]
https://www.figma.com/design/SacZjN10goX2lahJrmjWC0/Flyt--%3E-Ideation?node-id=1117-139714&t=wKCLRU4ELQ1c3LAZ-4

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit 18dc87a in TEST env.
Some options in the right-click menu for green cards should be disabled/hidden.

![image](https://github.com/user-attachments/assets/3261981b-bc2e-4bab-83b1-90bde3586ce3)

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test again. Thanks for feedback. I removed the backspace icon until the delete shortcut has been implemented. We have a separate issue for the copy and paste tutorial. I had a talk with Vetle and that is a good enough tutorial for now.

**Comment by KaterynaBasik** [comment]
Tested in Test env:
Here are some results from my end. Needs to be discussed 

1. Sometimes right-click menu appears far from the selected card

![image](https://github.com/user-attachments/assets/34f615e8-9edb-43ba-a261-c550460ee33c)
![image](https://github.com/user-attachments/assets/4dacb017-3801-4f25-9dc0-5f6daf75792d)

2. Regardless of what user choses while adding (`Add - Left` or `Add- Right`), a new card is added to the left. It works same way in production
![image](https://github.com/user-attachments/assets/cfdb227a-a76a-4bc9-8c5e-a9d75c25a140)

3. Opened right-click menu is disappeared when user click LMB somewhere but isn't disappeared when user holds LMB and move canvas

4.  By doing` Ctrl+C` -> `Ctrl+V` I changed the default SIPOC order somehow. Trying to reproduce this case
![image](https://github.com/user-attachments/assets/6d327692-65e5-4f92-b5cc-dc2908138797)

5. Process goes crazy when deleting main activity with choice cards
![image](https://github.com/user-attachments/assets/36dd5e62-a8d2-42ac-ab66-38428ff4c266)

6. Sometimes when adding a choice card to the Main activity it creates only one sub-activity
![image](https://github.com/user-attachments/assets/c2fe55a6-ef78-4800-ba57-8977b323e9ae)

Discuss: 

- [ ] What do we do with `Left` and `Right` options?
- [ ] Should PQIRs be copied as well?
- [ ] What is the value of copying choice card without it's connected alternatives?
- [ ] What is the value of `Add` action in the right-click menu if this can be done by existing functionality with fewer steps?

**Comment by nesadrian** [comment]
@KaterynaBasik 
1. Do you know how to reproduce this? I have not encountered this issue yet.
2. The cards are being added in the right order, but not displayed in the right order. There is an issue on this here #813 
3, 5: I'll fix it.
4, 6, 7: From the testing I have done these all seems to be connected to the same problem. I'll fix it.

As discussed in the meeting the Add action serves as a secondary option for users who prefer to do it this way even though it's slower

**Comment by KaterynaBasik** [comment]
> [@KaterynaBasik](https://github.com/KaterynaBasik)
> 
> 1. Do you know how to reproduce this? I have not encountered this issue yet.

I can't reproduce this anymore  🤔😃

**Comment by nesadrian** [comment]
@QiJin-Bouvet @KaterynaBasik This is ready for test

**Comment by KaterynaBasik** [comment]
Tested in Test
- 1,3,4,5,6: fixed
- 2: no changes, same behavior as described 
- 7:  Copy/Paste doesn't delete all connected cards anymore. Description doesn't copied to a new card but I guess it will be implemented in   #812

**Comment by nesadrian** [comment]
@KaterynaBasik  Ready for test. Main activity copy paste has been fixed. I have also removed the option to add cards to the left of choice childrens as discussed. Number 2 will be fixed in it's separate issue.

**Comment by KaterynaBasik** [comment]
Tested in Test

- [x] `Add`-`Left` option is not available now
