### ISSUE TITLE
Remove unused stores

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#808]
Flyt migrated from easy-peasy stores to TanStack Query a long time ago. We still use a store for snack messages, but it's about time we removed the unused ones.

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Snack messages should be tested to be sure that they still works the same.

**Comment by QiJin-Bouvet** [comment]
@nesadrian Can you list all the snack messages here in case I miss some.
* card copied
* card added
* anything more?

**Comment by nesadrian** [comment]
@QiJin-Bouvet Since at least one of them work, the rest will too in this case

**Comment by QiJin-Bouvet** [comment]
Tested with commit 04da6b2 in TEST.
The snack messages works fine.
