### ISSUE TITLE
Improve copy paste error snackmessage

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#817]
The current messages the user get when trying to paste a invalid content is not very descriptive.

![Image](https://github.com/user-attachments/assets/a23bb77d-0789-48b5-8b6c-e13d8b45b74f)
![Image](https://github.com/user-attachments/assets/1808e64b-e382-4010-b940-42234b45b1de)

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit d1bbfbc in TEST env.
Error message shown as below:

![Image](https://github.com/user-attachments/assets/6ed9ebdd-a7b8-4fcd-a3d8-7bb8505b9f30)
