### ISSUE TITLE
Process Hierarchy Model

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#819]
[Design](https://www.figma.com/design/SacZjN10goX2lahJrmjWC0/Flyt--%3E-Ideation?node-id=2320-189919&t=bqxwBHRjQfnWoqUt-4)

**Comment by QiJin-Bouvet** [comment]
Please change the ordering of processes in the connect process window to Last modified on top, and the oldest on the bottom.

![Image](https://github.com/user-attachments/assets/479a8bb6-c2d5-49ec-ab9d-42f5b6efd48d)

**Comment by QiJin-Bouvet** [comment]
It will be more convenient if user can choose multiple processes to connect on one card, so they don't need to do it multiple times.

**Comment by QiJin-Bouvet** [comment]
When linked process changed name, it should be updated in the current process.

**Comment by KaterynaBasik** [comment]
@sir-larsen

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Note that the issues you have mentioned is still being fixed on the backend: #803

**Comment by QiJin-Bouvet** [comment]
Tested with commit a3b7c9f in TEST.
* Text should shown in Italic font instead of <i> and </i>
* No chips shown for selected user/label in filter
* when no process match filter, a grey filed shown

![Image](https://github.com/user-attachments/assets/71f795fb-f52b-4a96-b4e2-fd4edceb72ce)

![Image](https://github.com/user-attachments/assets/869a8fa3-2b1a-49d1-aca1-13d341a139b6)

![Image](https://github.com/user-attachments/assets/867cc577-2bf7-46c3-a6ea-0bc7b115d5a0)

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test. Please make sure that infinite loading and the other form steps works correctly here aswell since I did make some changes to that part of the code.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 13b3a96 in TEST.
Fixed:
* Text between < i > and < / i > is shown as bold
* selected user/label shown as chips in the top left corner
* UI improved when no matched process found
Need to fix:
* Horizontal and vertical scrolling bar shown at the step before confirming connection
* Still not able to fill all fields of a SubActivity/Waiting card at the same time

![Image](https://github.com/user-attachments/assets/26c78685-31e8-434e-a1ac-4771d86ab460)

**Comment by QiJin-Bouvet** [comment]
For me, the scrollbars are always there. But the thumb is only available when there is really need to scroll. 

![Image](https://github.com/user-attachments/assets/b95ea2e9-6bdb-4930-8e56-7c367144049b)

**Comment by nesadrian** [comment]
There is a bug that causes the process to not center when opening the "Connect Process" window in the linked processes page in chromium-based browsers. I suspect upgrading to the newest reactflow version will fix this. [Here](https://reactflow.dev/whats-new/2024-09-26) is a related patch note.

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit c1ae181 in TEST env.
Process Hierarchy Model works fine.
Content been removed problem will be solved in issue #832
