### ISSUE TITLE
Redesign sidebar

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#825]
We are moving everything except PQIR's to the cards themselves. To make PQIR's easier to work with we have decided to redesign the sidebar.

Design: [Figma](https://www.figma.com/design/SacZjN10goX2lahJrmjWC0/Flyt--%3E-Ideation?node-id=2440-198786&t=x6wzDhVZeyCm2aai-4)

Closes #526 #158 

Discuss: #315

**Comment by nesadrian** [comment]
Blocked until #829 is done

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit a98a77f in TEST env.
* text exit the boundary when PQIR are collapsed, eg. process 504. Maybe just show some text in beginning, and with ellipsis when the PQIR is collapsed.
* Solved problem and risk are invisible in the card
* And I suggest to give some warning like 'it will delete the PQIR from all cards/the whole process' in the deleting popup. So user understand it is a action affect the process, not a specific card.

![Image](https://github.com/user-attachments/assets/c3467c0f-92b7-4f79-9d8a-eb5419c62dfa)

![Image](https://github.com/user-attachments/assets/760481ec-e702-4c7b-86e9-e6f83fafd36b)

![Image](https://github.com/user-attachments/assets/7baa6c41-2e51-4fd2-ab4a-460c969e731e)

**Comment by QiJin-Bouvet** [comment]
Tested with commit 857c422 in TEST.
Problem listed above are solved.

BUT, can you add information tooltips for those different buttons, like in Prod environment, which will be useful for new users.
* trash button: Delete selected PQIR
* square button: Mark as solved
* + button: Link PQIR with this card
* - button: Unlink PQIR with this card

![Image](https://github.com/user-attachments/assets/1fa0a570-c640-4810-b26c-ca60dd2cddb5)
![Image](https://github.com/user-attachments/assets/5523a8f4-0e14-48de-8874-b15de07cbf83)

**Comment by nesadrian** [comment]
@QiJin-Bouvet Good suggestion. I also added hover text to the PQIR selector buttons. It's in test now.

**Comment by QiJin-Bouvet** [comment]
Tested with commit 4c4de56 in TEST env.
Looks good. 👍

**Comment by SIVN1** [comment]
@AnjaliPandit20 Verified in test and QA environment, Works fine

<img width="944" alt="Image" src="https://github.com/user-attachments/assets/c2513739-bc9f-4ed3-8f11-9649abf77046" />

CC: @ThomasBracho1987 @luan-droid @srvEq

**Comment by luan-droid** [comment]
I can confirm that it works fine. Tested it QA and Test env.
