### ISSUE TITLE
Fix main activity

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#837]

**Comment by nesadrian** [comment]
@QiJin-Bouvet This is ready for test. Main activities should be able to be dropped on top of other main activities and switch order now.

**Comment by luan-droid** [comment]
It is only possible to rearrange the mainactivity card to the right, not to the left. Tested it in Test env. 
https://github.com/user-attachments/assets/34a645a2-e0d3-403e-a2ea-534a801b6494


@SIVN1 @ThomasBracho1987 

CC: @AnjaliPandit20 @SIJAIEQUINOR

**Comment by luan-droid** [comment]
It works fine. Sub issue has been created #876 

@ThomasBracho1987 @SIVN1
