### ISSUE TITLE
Redesign sidebar: MD description & copy paste

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#845]
https://github.com/equinor/flyt/issues/825#issuecomment-2527385960

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit d20ba26 in TEST env.
Works fine. 👍

**Comment by luan-droid** [comment]
It works fine. Tested it on QA and in Test

@AnjaliPandit20 @ThomasBracho1987 @SIVN1 @SIJAIEQUINOR

**Comment by SIVN1** [comment]
Verified in Prod. Able to copy and paste in description. Works fine

<img width="924" alt="Image" src="https://github.com/user-attachments/assets/9839742b-327c-4b99-ab43-2b537c565795" />

CC: @AnjaliPandit20 @luan-droid @ThomasBracho1987
