### ISSUE TITLE
Hidden nodes cause crashes

### ISSUE THREAD

**Issue by nesadrian** [equinor/flyt#849]
A bug that causes hidden nodes to crash flyt has oocured after the refactoring that was done when developing the linked processes.

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit f65fe2e in TEST env.
Works fine. No crash when moving hidden nodes.

**Comment by QiJin-Bouvet** [comment]
Tested with commit b237bc2 in QA env.
Works fine.

**Comment by SIVN1** [comment]
@AnjaliPandit20 Verified in Test and QA environment, Working fine. No crash when moving hidden nodes

<img width="953" alt="Image" src="https://github.com/user-attachments/assets/3c18730d-2bf1-422d-8719-a52e71fa25e2" />

CC: @ThomasBracho1987 @luan-droid @srvEq

**Comment by SIVN1** [comment]
Verified in Prod. Working fine

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/b777f4ab-cbfc-4038-8c33-db2fbd1f52d9" />

CC: @AnjaliPandit20 @ThomasBracho1987 @SIVN1
