### ISSUE TITLE
Fix: Client error when dragging card far away

### ISSUE THREAD

**Issue by QiJin-Bouvet** [equinor/flyt#851]
When dragging a card far away outside canvas, a error shown as 'An error occurred on client'.
Problem found when testing #834 with commit 759d01c in QA env. Since code is not released, problem doesn't happen in Prod.
Console error shown as below: 

![Image](https://github.com/user-attachments/assets/f67f7678-484d-402b-8e5a-0aa7fe4014ff)

**Comment by nesadrian** [comment]
@QiJin-Bouvet Ready for test

**Comment by QiJin-Bouvet** [comment]
Tested with commit efe858f in TEST.
Problem not happen any more.

**Comment by SIVN1** [comment]
@AnjaliPandit20 Verified in test and QA env, Working fine. Not getting error when dragging the cards

CC: @ThomasBracho1987 @luan-droid @srvEq

**Comment by SIVN1** [comment]
Verified in Prod. Works fine. 

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/950c93f8-9d65-4216-b361-c08b8f27e18a" />

CC: @AnjaliPandit20 @ThomasBracho1987 @luan-droid
