### ISSUE TITLE
Adding new cards sometimes does not work.

### ISSUE THREAD

**Issue by SjoenH** [equinor/flyt#88]
**User input by several people:**
Noen ganger – “umulig” å få til å flytte eksisterende  bokser (blå – gule). Eller finnes et eget triks/snet ?

**User input**
> While assisting user in mapping ((projects/81) it was only possible for user to add new yellow cards under the blue card. The card was afterwards moved to bottom of the other yellow cards. I observed it more than once during mapping. However, I have not been able to replicate this issue myself in projects/105.

[VSM-155](https://equinor-sds-si.atlassian.net/browse/vsm-155)

**Comment by knudsvik** [comment]
Alternative solution: Present some message to the user that they should not have many things open, like Teams etc.
